### ISSUE TITLE
Thunderbird snap ignores ignite

### ISSUE THREAD

**Issue by ondras12345** [73/ignite#3]
I have recently updated to Ubuntu 24.04 and switched from X to Wayland.
After updating ignite and installing Window Calls, it works perfectly, except when I open links from thunderbird. In that case, the link opens, but in an incorrect workspace.
My guess would be that this has something to do with the fact that thunderbird is now a snap in Ubuntu 24.04.
Has anyone encountered this before? Is there a fix / workaround?

I have added this line to the `ignite` script:
```
date -Iseconds >> ~/ignite.log
```
and it seems like `ignite` does not run at all when a link is clicked in thunderbird.
However, when I set
```
xdg-settings set default-web-browser org.qutebrowser.qutebrowser.desktop
```
links from thunderbird do open in qutebrowser, so it does not completely ignore the default browser setting.

I have ignite in [`~/bin/ignite`](https://github.com/ondras12345/dotfiles/blob/5b02b9c54414722c3182950c5c6735524354f0bb/bin/ignite), `~/bin` is in my `PATH` and the [.desktop file looks like this](https://github.com/ondras12345/dotfiles/blob/linux/.local/share/applications/ignite.desktop).

**Comment by 73** [comment]
Hi @ondras12345,

thank you for the report. Currently I do not own a system with `snapd` (very much on purpose). However, I am experiencing [a very similar issue](https://github.com/73/ignite/issues/3) with flatpak. You could try to run:
```sh
xdg-mime default ignite.desktop x-scheme-handler/http
xdg-mime default ignite.desktop x-scheme-handler/https
```
I have it from here: https://forum.snapcraft.io/t/default-browser-not-used-from-within-snap/4347/40

**Comment by ondras12345** [comment]
Thanks for looking into it!

I also like to avoid snaps. In fact, I have no other snap app installed to do testing with.

> However, I am experiencing [a very similar issue](https://github.com/73/ignite/issues/3) with flatpak

For future reference, I believe you meant to link https://github.com/73/ignite/issues/4

Unfortunately, those `xdg-mime` commands did not help.
Thinking about it, the snap sandbox might be preventing thunderbird from executing `$HOME/bin/ignite`, which causes it to then fall back to firefox. Otherwise, I can't explain why qutebrowser would work.
I'll do some further experiments and let you know if I discover something.

**Comment by 73** [comment]
I would appreciate the insight. However, the Mozilla team itself has a ppa for Thunderbird and different versions of Firefox [here](https://launchpad.net/~mozillateam/+archive/ubuntu/ppa?field.series_filter=noble).

**Comment by 73** [comment]
I had a little time today. One is able to open external links from Thunderbird with a non-default browser following [this procedure](https://www.reddit.com/r/Thunderbird/comments/1b2iqoj/comment/ksmi2ao/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).

However, please apply the changes from #5 to your setup and check whether it fixes things for snap, too.

**Comment by ondras12345** [comment]
Commenting out `Hidden=true` in the .desktop file did the trick for both snap and flatpak apps. No need to fiddle with thunderbird settings or `gio mime`. Thanks!

**Comment by 73** [comment]
Glad we figured this one out.
